/**
 * Tarifas oficiais da Viação Praiana
 * Fonte: Informativo Oficial de Tarifas — vigência a partir de 19/07/2026
 * Homologado pela SIE/SC
 *
 * Para atualizar valores depois de um reajuste:
 * 1) Altere o campo `tarifa` aqui, ou
 * 2) Use o botão de engrenagem no sistema (as alterações ficam neste computador).
 */
window.PRAIANA = {
  vigencia: "19/07/2026",
  fonte:
    "Informativo Oficial de Tarifas Praiana v3 — homologado pela SIE/SC",
  estudantePercentual: 50,
  postos: [
    { id: "itajai", nome: "Itajaí" },
    { id: "camboriu", nome: "Camboriú" },
    { id: "bc", nome: "Balneário Camboriú" },
    { id: "itapema", nome: "Itapema" },
    { id: "porto-belo", nome: "Porto Belo" },
    { id: "tijucas", nome: "Tijucas" },
    { id: "picarras", nome: "Piçarras" },
    { id: "floripa", nome: "Florianópolis" },
    { id: "todas", nome: "Todas as linhas" },
  ],
  trechos: [
    {
      id: "3651-camboriu-itajai",
      codigo: "3651",
      linha: "Camboriú × Itajaí",
      origem: "Camboriú",
      destino: "Itajaí",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "3651-itajai-camboriu",
      codigo: "3651",
      linha: "Itajaí × Camboriú",
      origem: "Itajaí",
      destino: "Camboriú",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0521-bc-itajai",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Balneário Camboriú",
      destino: "Itajaí",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0521-itajai-bc",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Itajaí",
      destino: "Balneário Camboriú",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0521-bc-urbano",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Balneário Camboriú",
      destino: "Balneário Camboriú (urbano)",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0521-itajai-urbano",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Itajaí",
      destino: "Itajaí (urbano)",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0521-itapema-bc",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Itapema",
      destino: "Balneário Camboriú",
      tarifa: 8.1,
      grupo: "intermunicipal",
    },
    {
      id: "0521-bc-itapema",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Balneário Camboriú",
      destino: "Itapema",
      tarifa: 8.1,
      grupo: "intermunicipal",
    },
    {
      id: "0521-itapema-itajai",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Itapema",
      destino: "Itajaí",
      tarifa: 10.6,
      grupo: "intermunicipal",
    },
    {
      id: "0521-itajai-itapema",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Itajaí",
      destino: "Itapema",
      tarifa: 10.6,
      grupo: "intermunicipal",
    },
    {
      id: "0521-pb-itapema",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Porto Belo",
      destino: "Itapema",
      tarifa: 4.8,
      grupo: "intermunicipal",
    },
    {
      id: "0521-itapema-pb",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Itapema",
      destino: "Porto Belo",
      tarifa: 4.8,
      grupo: "intermunicipal",
    },
    {
      id: "0521-pb-bc",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Porto Belo",
      destino: "Balneário Camboriú",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0521-bc-pb",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Balneário Camboriú",
      destino: "Porto Belo",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0521-pb-itajai",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Porto Belo",
      destino: "Itajaí",
      tarifa: 11.1,
      grupo: "intermunicipal",
    },
    {
      id: "0521-itajai-pb",
      codigo: "0052-01",
      linha: "Porto Belo × Itajaí",
      origem: "Itajaí",
      destino: "Porto Belo",
      tarifa: 11.1,
      grupo: "intermunicipal",
    },
    {
      id: "3642-bem-bom-bc",
      codigo: "0364-02",
      linha: "Seletivo Bem Bom",
      origem: "Itajaí",
      destino: "Balneário Camboriú (Bem Bom)",
      tarifa: 16.9,
      grupo: "seletivo",
    },
    {
      id: "3642-bem-bom-itajai",
      codigo: "0364-02",
      linha: "Seletivo Bem Bom",
      origem: "Balneário Camboriú",
      destino: "Itajaí (Bem Bom)",
      tarifa: 16.9,
      grupo: "seletivo",
    },
    {
      id: "0723-monte-alegre-itajai",
      codigo: "0723",
      linha: "Monte Alegre × Unimed BC",
      origem: "Monte Alegre",
      destino: "Itajaí",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0723-itajai-monte-alegre",
      codigo: "0723",
      linha: "Monte Alegre × Unimed BC",
      origem: "Itajaí",
      destino: "Monte Alegre",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0723-monte-alegre-bc",
      codigo: "0723",
      linha: "Monte Alegre × Unimed BC",
      origem: "Monte Alegre",
      destino: "Unimed BC",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0723-bc-monte-alegre",
      codigo: "0723",
      linha: "Monte Alegre × Unimed BC",
      origem: "Balneário Camboriú",
      destino: "Monte Alegre",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0365-rio-pequeno-camboriu",
      codigo: "0365-00",
      linha: "Rio Pequeno",
      origem: "Rio Pequeno",
      destino: "Camboriú",
      tarifa: 4.8,
      grupo: "intermunicipal",
    },
    {
      id: "0365-camboriu-rio-pequeno",
      codigo: "0365-00",
      linha: "Rio Pequeno",
      origem: "Camboriú",
      destino: "Rio Pequeno",
      tarifa: 4.8,
      grupo: "intermunicipal",
    },
    {
      id: "0365-rio-pequeno-bc",
      codigo: "0365-00",
      linha: "Rio Pequeno",
      origem: "Rio Pequeno",
      destino: "Balneário Camboriú",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0365-bc-rio-pequeno",
      codigo: "0365-00",
      linha: "Rio Pequeno",
      origem: "Balneário Camboriú",
      destino: "Rio Pequeno",
      tarifa: 8.45,
      grupo: "intermunicipal",
    },
    {
      id: "0365-rio-pequeno-itajai",
      codigo: "0365-00",
      linha: "Rio Pequeno",
      origem: "Rio Pequeno",
      destino: "Itajaí",
      tarifa: 10.6,
      grupo: "intermunicipal",
    },
    {
      id: "0365-itajai-rio-pequeno",
      codigo: "0365-00",
      linha: "Rio Pequeno",
      origem: "Itajaí",
      destino: "Rio Pequeno",
      tarifa: 10.6,
      grupo: "intermunicipal",
    },
    {
      id: "0523-tijucas-pb",
      codigo: "0052-03",
      linha: "Porto Belo × Tijucas",
      origem: "Tijucas",
      destino: "Porto Belo",
      tarifa: 8.1,
      grupo: "intermunicipal",
    },
    {
      id: "0523-pb-tijucas",
      codigo: "0052-03",
      linha: "Porto Belo × Tijucas",
      origem: "Porto Belo",
      destino: "Tijucas",
      tarifa: 8.1,
      grupo: "intermunicipal",
    },
    {
      id: "0445-itapema-pb",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Itapema",
      destino: "Porto Belo",
      tarifa: 6.6,
      grupo: "floripa",
    },
    {
      id: "0445-pb-itapema-floripa",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Porto Belo",
      destino: "Itapema",
      tarifa: 6.6,
      grupo: "floripa",
    },
    {
      id: "0445-itapema-tijucas",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Itapema",
      destino: "Tijucas",
      tarifa: 13.25,
      grupo: "floripa",
    },
    {
      id: "0445-tijucas-itapema",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Tijucas",
      destino: "Itapema",
      tarifa: 13.25,
      grupo: "floripa",
    },
    {
      id: "0445-itapema-ganchos",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Itapema",
      destino: "Encruzilhada Ganchos",
      tarifa: 20.3,
      grupo: "floripa",
    },
    {
      id: "0445-ganchos-itapema",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Encruzilhada Ganchos",
      destino: "Itapema",
      tarifa: 20.3,
      grupo: "floripa",
    },
    {
      id: "0445-itapema-tijuquinhas",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Itapema",
      destino: "Tijuquinhas",
      tarifa: 22.35,
      grupo: "floripa",
    },
    {
      id: "0445-tijuquinhas-itapema",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Tijuquinhas",
      destino: "Itapema",
      tarifa: 22.35,
      grupo: "floripa",
    },
    {
      id: "0445-itapema-floripa",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Itapema",
      destino: "Florianópolis (TRM)",
      tarifa: 33.5,
      grupo: "floripa",
    },
    {
      id: "0445-floripa-itapema",
      codigo: "0445-00",
      linha: "Florianópolis × Itapema",
      origem: "Florianópolis",
      destino: "Itapema",
      tarifa: 33.5,
      grupo: "floripa",
    },
    {
      id: "0445-pb-tijucas",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Porto Belo",
      destino: "Tijucas",
      tarifa: 13.65,
      grupo: "floripa",
    },
    {
      id: "0445-tijucas-pb-floripa",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Tijucas",
      destino: "Porto Belo",
      tarifa: 13.65,
      grupo: "floripa",
    },
    {
      id: "0445-pb-ganchos",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Porto Belo",
      destino: "Encruzilhada Ganchos / Tijuquinhas",
      tarifa: 15.7,
      grupo: "floripa",
    },
    {
      id: "0445-ganchos-pb",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Encruzilhada Ganchos",
      destino: "Porto Belo",
      tarifa: 15.7,
      grupo: "floripa",
    },
    {
      id: "0445-pb-floripa",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Porto Belo",
      destino: "Florianópolis (TRM)",
      tarifa: 26.9,
      grupo: "floripa",
    },
    {
      id: "0445-floripa-pb",
      codigo: "0445-00",
      linha: "Florianópolis × Itapema",
      origem: "Florianópolis",
      destino: "Porto Belo",
      tarifa: 26.9,
      grupo: "floripa",
    },
    {
      id: "0445-tijucas-ganchos",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Tijucas",
      destino: "Encruzilhada Ganchos",
      tarifa: 7.05,
      grupo: "floripa",
    },
    {
      id: "0445-ganchos-tijucas",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Encruzilhada Ganchos",
      destino: "Tijucas",
      tarifa: 7.05,
      grupo: "floripa",
    },
    {
      id: "0445-tijucas-tijuquinhas",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Tijucas",
      destino: "Tijuquinhas",
      tarifa: 9.1,
      grupo: "floripa",
    },
    {
      id: "0445-tijuquinhas-tijucas",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Tijuquinhas",
      destino: "Tijucas",
      tarifa: 9.1,
      grupo: "floripa",
    },
    {
      id: "0445-tijucas-floripa",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Tijucas",
      destino: "Florianópolis (TRM)",
      tarifa: 20.3,
      grupo: "floripa",
    },
    {
      id: "0445-floripa-tijucas",
      codigo: "0445-00",
      linha: "Florianópolis × Itapema",
      origem: "Florianópolis",
      destino: "Tijucas",
      tarifa: 20.3,
      grupo: "floripa",
    },
    {
      id: "0445-ganchos-floripa",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Encruzilhada Ganchos",
      destino: "Florianópolis (TRM)",
      tarifa: 13.25,
      grupo: "floripa",
    },
    {
      id: "0445-floripa-ganchos",
      codigo: "0445-00",
      linha: "Florianópolis × Itapema",
      origem: "Florianópolis",
      destino: "Encruzilhada Ganchos",
      tarifa: 13.25,
      grupo: "floripa",
    },
    {
      id: "0445-tijuquinhas-floripa",
      codigo: "0445-00",
      linha: "Itapema × Florianópolis",
      origem: "Tijuquinhas",
      destino: "Florianópolis (TRM)",
      tarifa: 11.2,
      grupo: "floripa",
    },
    {
      id: "0445-floripa-tijuquinhas",
      codigo: "0445-00",
      linha: "Florianópolis × Itapema",
      origem: "Florianópolis",
      destino: "Tijuquinhas",
      tarifa: 11.2,
      grupo: "floripa",
    },
    {
      id: "0134-picarras-volta-grande",
      codigo: "0134-02",
      linha: "Piçarras × Volta Grande",
      origem: "Piçarras",
      destino: "Volta Grande",
      tarifa: 7.9,
      grupo: "litoral-norte",
    },
    {
      id: "0134-volta-grande-picarras",
      codigo: "0134-02",
      linha: "Volta Grande × Piçarras",
      origem: "Volta Grande",
      destino: "Piçarras",
      tarifa: 7.9,
      grupo: "litoral-norte",
    },
    {
      id: "0299-pedra-picarras",
      codigo: "0299-00",
      linha: "Pedra de Amolar × Piçarras",
      origem: "Pedra de Amolar",
      destino: "Piçarras",
      tarifa: 7.9,
      grupo: "litoral-norte",
    },
    {
      id: "0299-picarras-pedra",
      codigo: "0299-00",
      linha: "Piçarras × Pedra de Amolar",
      origem: "Piçarras",
      destino: "Pedra de Amolar",
      tarifa: 7.9,
      grupo: "litoral-norte",
    },
    {
      id: "0100-circular-itapema",
      codigo: "0100",
      linha: "Circular Itapema",
      origem: "Itapema",
      destino: "Circular Itapema (municipal)",
      tarifa: 4.0,
      grupo: "municipal",
    },
    {
      id: "0500-seletivo-itapema",
      codigo: "0500",
      linha: "Seletivo Itapema",
      origem: "Itapema",
      destino: "Seletivo Itapema",
      tarifa: 4.5,
      grupo: "seletivo",
    },
    {
      id: "0600-circular-porto-belo",
      codigo: "0600",
      linha: "Circular Porto Belo",
      origem: "Porto Belo",
      destino: "Circular Porto Belo (tarifa zero)",
      tarifa: 0,
      grupo: "municipal",
    },
  ],
};
